### ISSUE TITLE
OperatorConsole.h seems to be out of date??

### ISSUE THREAD

**Issue by dudullz** [imatest/Operator-Console#9]
The VS solution failed to build (see blow the screenshot for error messages). It looks like the header file(s) are not updated with OperatorConsole.cpp file. 

Maybe there are other files need to be replaced?

![Errors_OperatorConsole](https://user-images.githubusercontent.com/2839042/92473909-2aff7680-f1d3-11ea-9f8b-ba0b90dbe9bd.png)

**Comment by tcumby** [comment]
I pushed some fixes to this an related issues. Please let me know if you are still having problems.
